msgGMS: "§f[§l§4Staff§r§f]: vous avez bien été mis en gamemode survival"
msgGMC: "§f[§l§4Staff§r§f]: vous avez bien été mis en gamemode créativer"
msgGMA: "§f[§l§4Staff§r§f]: vous avez bien été mis en gamemode aventure"
msgGMSP: "§f[§l§4Staff§r§f]: vous avez bien été mis en gamemode sprectateur"
msgNoPerm: "§f[§l§4ERROR§r§f]: vous n'avez pas la permission d'éxécuter cette commande"